development:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :tls: true
  :port: 587
  :authentication: plain
  :user_name: socialbiteevents@gmail.com
  :password: elsol100
production:
  :address: smtp.server.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass
